[project]
name = "bored-charts-example-full"
version = "0.1.0"
description = "A fuller example of a bored-charts project."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["bored-charts", "uvicorn>=0.30.5"]

[project.scripts]
bc-example = "bcexample.app:entrypoint"
