name: Setup python (rye)
description: Setup python with rye (including caching)

inputs:
  python-version:
    description: python version
    default: "3.12"
  extra-cache:
    description: extra globs to cache
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - run: >
        [ -f .python-version ] || echo "${{ inputs.python-version }}" > .python-version
      shell: bash

    - id: setup-rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true

    - run: rye sync
      shell: bash

    - name: set-cache-name
      id: set-cache-name
      run: |
        cache_name="$(echo '${{ inputs.extra-cache }}' | tr '\n' '-')"
        echo "cache-name=$cache_name" >>$GITHUB_OUTPUT
      shell: bash

    - if: ${{ 'inputs.extra-cache' != '' }}
      name: extra-cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.extra-cache }}
        key: ${{ runner.os }}-${{ steps.set-cache-name.outputs.cache-name }}
